hotwax/order-routing

src/App.vue
src/components/RouteMenu.vue
src/theme/variables.css
src/views/BrokeringQuery.vue
src/views/BrokeringRoute.vue
src/views/Settings.vue
src/views/Tabs.vue

Improved: UI for the app to use basic routing(#4)

---

src/api/index.ts
src/store/modules/user/actions.ts
src/views/BrokeringRuns.vue
src/views/Login.vue

Improved: handling of token in the response(#14)

---

src/services/RoutingService.ts
src/store/modules/orderRouting/OrderRoutingState.ts
src/store/modules/orderRouting/actions.ts
src/store/modules/orderRouting/getters.ts
src/store/modules/orderRouting/index.ts
src/store/modules/orderRouting/mutations.ts
src/views/BrokeringRoute.vue
src/views/BrokeringRuns.vue

Closes #
Added support to fetch the currentRoutingRun information is not already present on page refresh

Fixed: case that on routing page refresh the routing information is not available

---

src/store/modules/orderRouting/actions.ts
src/views/BrokeringRoute.vue

Fixed: case to update current group state when making any change on group level

---

src/components/ArchivedRoutingModal.vue
src/services/RoutingService.ts
src/store/modules/orderRouting/actions.ts
src/store/modules/orderRouting/getters.ts
src/utils/index.ts
src/views/BrokeringRoute.vue
src/views/BrokeringRuns.vue

Improved: support to fetch route with current group and update routes in bulk(feat/route)

---

src/services/RoutingService.ts
src/store/modules/orderRouting/actions.ts
src/store/modules/orderRouting/index.ts

Improved: the endpoint to fetch the schedule information for a group(#51)

---

src/services/RoutingService.ts
src/views/BrokeringRoute.vue

Implemented: support to run the schedule now(#58)

---

src/views/BrokeringQuery.vue

Fixed: the details page when hitting a url directly for a different group than the group stored in current state(#76)

---

src/components/RoutingHistoryModal.vue
src/locales/en.json
src/services/RoutingService.ts
src/store/RootState.ts
src/store/modules/orderRouting/actions.ts
src/store/modules/user/actions.ts
src/store/modules/util/actions.ts
src/theme/variables.css
src/views/BrokeringRoute.vue
src/views/BrokeringRuns.vue

Implemented: support to display searchbar and product store filters on the groups page and filter groups(#99)

---

src/store/modules/orderRouting/actions.ts
src/views/BrokeringRoute.vue
src/views/BrokeringRuns.vue

Closes #
Added support to display the runTime and frequency for a group
After:

Implemented: support to display the runTime and frequency for a group on the list page

---

src/store/modules/orderRouting/actions.ts
src/utils/index.ts

Closes #
Added support in the sort function to sort on the passed field and if not present then sort on sequenceNum.
Also improved sorting for groups to use runTime parameter for sorting

Improved: code to sort the groups on the basis of runTime and improved the sort function to sort the array on the provided field

---

src/locales/en.json
src/views/BrokeringRoute.vue

Closes #119
Remove the method to show the alert on clicking save button on routing list page and save the changes directly.

Improved: save button action to not show an alert before save on routing list page(#119)

---

src/locales/en.json
src/views/BrokeringQuery.vue

Closes #117 
- Display `Active` with success color when rule status is `RULE_ACTIVE`
- Display `Archived` with warning color when status is `RULE_ARCHIVED`
- Display `Draft` with default color when status is `RULE_DRAFT`
After:

Improved: UI to display the rule status in the menu list(#117)

---

src/views/BrokeringQuery.vue
src/views/BrokeringRoute.vue

Fixed: multiple alerts getting rendered in DOM when moving back-and-forth from route and query page

---

src/views/BrokeringRoute.vue

Improved: code to add support for checking oms connection when using runNow feature

---

src/store/modules/orderRouting/actions.ts
src/views/BrokeringRuns.vue

Related Issue #135 
Added check to wait until the updated information is being fetched and make the productStoreId dynamic when creating a new run.

Fixed: run not displayed after creation immediately(#135)

---

src/views/BrokeringRuns.vue
src/views/Settings.vue

Related Issue #149 
Added check to display storeName if available otherwise display productStoreId
Before:
After:

Fixed: case to display productStoreId in case the storeName is not available(#149)

---

src/store/modules/orderRouting/actions.ts
src/views/BrokeringQuery.vue

Fixed: issue in filter option persistence and field overridden issue in filter and sort options(#146)

---

src/components/GroupHistoryModal.vue
src/locales/en.json
src/views/BrokeringRoute.vue

Related Issue #145 
- When finding the index number for routes we honor the active and draft routes, but as the route is unarchived but not saved in the state, then the index for the route is not found resulting in displaying NaN.
- Added toast message to not redirect the user to the details page in the above case
- Fixed a case when timeTillJob is not found

Fixed: support to not open the details page for unarchived route(#145)

---

src/views/BrokeringRoute.vue

Related Issue #147 
This change will allow user to run the service directly without scheduling it in active state
Clicking runNow when the group does not have a scheduler configured(job is not already scheduled) results in an error. Improved support to check whether the scheduler is configured for the group or not, if not then before calling runNow service, scheduling the job as draft to configure the scheduler and then making the runNow request.
Added check to not allow user to select the schedule if the job is not present or job status is draft.

Improved: logic to run the job successfully on clicking runNow(#147)

---

src/locales/en.json
src/theme/variables.css
src/views/BrokeringRuns.vue

Related Issue #156
After:
Removed search option:
Removed product Store options when having a single productStore:

Improved: check to display productStore options only if having multiple options to select from and removed the search option from the page(#156)

---

src/locales/en.json
src/views/BrokeringQuery.vue

Related Issue #158 
- Moved auto cancel days toggle inside the unfillable items card
- Added support to allow users to only add `autoCancelDays` only when `clearAutoCancelDays` is off. (https://github.com/hotwax/order-routing-rules/issues/158#issuecomment-2042279565)
After:

Improved: UI to move auto cancel days toggle inside unfillable items card(#158)

---

src/views/BrokeringQuery.vue

When applying proximity filter the operator passed is `equals` but we don't need the distance calculation logic to check for exact distance.
Changed the operator for proximity filter to `less-equals` as we need to check for all the facilities withing that specified distance.

Fixed: operator when selecting proximity filter

---

src/views/BrokeringQuery.vue

Related Issue #167
As the ion-chip and ion-select has some padding between them when using ion-select inside ion-chip, if the user clicks outside of ion-select, but inside ion-chip in the padding part, the ion-select popover does not opens up.
Added support to override the ion-select click event and added a click event on ion-chip to programmatically trigger the ion-select event when user performs a click action anywhere inside ion-chip

Fixed: the click issue in ion-select when used inside ion-chip(#167)

---

src/utils/index.ts
src/views/BrokeringRuns.vue
src/views/Settings.vue

Related Issue #118 
As Intl is set in 24-hour format and luxon uses the format set at Intl does it was returning the time in 24-hour format. Overridden the behaviour by adding hourCycle property to always use 12-hour format.
- Also added a check to not result in error when time is undefined.
After:

Fixed: the 12-hour format issue when using specific formatting options from luxon(#188)

---

src/components/ArchivedRoutingModal.vue
src/views/BrokeringRoute.vue

Related Issue #181 
- As we need to save the unarchived routings on clicking backdrop, thus added support to directly update the routing status state on clicking unarchive button instead of waiting for the user to close the modal, becuase after unarchiving multiple routings if user clicks backdrop the data is not passed to parent component and the routings are not updated.
- Improved the case to display archived routing card when we have all the routings as archived

Fixed: case related to updating archived routing and its UI(#181)

---

src/theme/variables.css
src/views/BrokeringQuery.vue
src/views/BrokeringRoute.vue

Related Issue #197 
- Added route name rename support on query page
- Moved the css to app level style file
- Changed the block button to fab button for saving the changes
- Improved check for auto cancel days to not allow negative values and added check for clearing the autoCancelDays
After:

Improved: UI for the rules page(#197)

---

src/views/BrokeringQuery.vue

Closes #
- Clicking rename for inventory rule name, should auto focus on the input

Implemented: support to autofocus on the input when updating rule name

---

src/components/PromiseFilterPopover.vue
src/views/BrokeringQuery.vue

Related Issue #197 
- Added check to not allow entering special characters in the alert input field
- Added support to only show the prefill values in promise date filter when the previously selected option and current option matches

Fixed: issue regarding decimal numbers can be entered in alert input(#197)

---

src/components/ArchivedRoutingModal.vue

Related Issue #181
When unarchiving, we are only updating the current route and not updating all the routes, thus updated all the routings on unarhive.

Fixed: archived routing cards to be dispalyed correctly after unarchiving a rule(#181)

---

src/components/AddInventoryFilterOptionsModal.vue
src/components/AddOrderRouteFilterOptions.vue
src/locales/en.json
src/views/BrokeringQuery.vue

If the enum data is missing then the label for the sort options is not displayed and the option selection modal is displayed empty.
Closes #
- Added empty state in option selection modal when the enum data is missing
- Added check to display the code if the enum label is missing
Before:
After:

Fixed: case to handle the case when enum data is missing for specific type

---

src/views/BrokeringQuery.vue

This issue occurs when we apply a new condition in the rule and update the same condition without refresh.
Fetched the latest information after updating a rule so to pass the seqId when updating the same filter again

Fixed: issue of duplicate filters getting applied on the rules

---

src/locales/en.json
src/views/BrokeringQuery.vue

Implemented: support to define the default action type for a rule

---

src/store/modules/orderRouting/actions.ts
src/store/modules/util/actions.ts

Closes #
Added pageSize param in all requests where we can have large number of records.

Fixed: issue in filters not being fetched by passing pageSize param

---

src/views/BrokeringRoute.vue

#138
Declared a variable to identify when the reordering is in progress and on the basis of same disabled the card so that all the click events defined on the card becomes inactive until reordering is not completed.
Defined a class to unset the opacity from the card, as when a card is disabled its opacity is changed, but in this case we do not want the users to know that the cards are disabled thus added a class to handle this case.
Using pointerup and down events to change the value of `isReordering` variable and added the pointerdown event on the reorder chip and pointerup event on the page, as the reordering will only be initiated from the chip and the pointerdown event can be triggered from any component on the page once reordering is started thus down event is defined on page level.

Implemented: support to disable the click event from the card when reordering is in progress(#138)

---

src/views/BrokeringRuns.vue

Changed the arrow icon (->) for the 'Create Brokering Run' button in the Order Routing app's Brokering Run page to a '+' icon.
Change Icon for "Create Brokering Run" Button #266

[Implemented]: Change Icon for 'Create Brokering Run' Button (#266)

---

src/views/BrokeringQuery.vue

#263 
Before: (Group is selected but is not visible on UI, as the has been unlinked from the Brokering group type)
After: (Group is visible when already selected in a rule, after being unlinked from the brokering group type)

Improved: code to display the group ID when that group is removed from parent group(#263)

---

src/views/BrokeringQuery.vue

When selecting brokering safety stock without selecting an operator, the default value passed in was equals, so fixed code to make the operator default value as greater in case of brokering safety stock filter
#

Fixed: issue in brokering safety stock filter to have greater as its default operator

---

.env.example
src/store/modules/orderRouting/actions.ts
src/views/BrokeringQuery.vue

#
Added an env entry to manage filters for which we need to have sort by as desc and handled support for the same when fetching and updating inventory rule filters

Implemented: support to have sortBy as desc for specific inventory filters
