package-lock.json, package.json
=> Immproved: ionic version to 7.6.0 and added apps-theme package

.firebaserc
=> Improved: directory naming for project

src/views/BrokeringQuery.vue
=> Updated: actions UI as per the updated changes in design

src/views/Login.vue
=> Fixed: login button not working on click

package-lock.json, package.json, src/main.ts, src/theme/variables.css, vue.config.js
=> Implemented: app version info support and imported apps theme(#32)

.env.example, src/services/RoutingService.ts, src/store/modules/orderRouting/getters.ts, src/views/BrokeringRoute.vue
Closes #39 
For now we have hardcoded options for cron expression, will handle dynamic cron expression creation in https://github.com/hotwax/order-routing-rules/issues/36
=> Implementes: support to schedule and update a job(#39)

src/App.vue, src/store/modules/orderRouting/actions.ts, src/store/modules/user/actions.ts, src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue, src/views/BrokeringRuns.vue
=> Implemented: loader and toast messages in the app(#46)

src/store/modules/orderRouting/actions.ts, src/views/BrokeringQuery.vue
=> Fixed: issue in sorting of inventory rules after update(#24)

src/store/modules/orderRouting/actions.ts, src/views/BrokeringQuery.vue
=> Fixed: issue when creating a new rule due to state update failure, and added a null check when checking for promise date filter(#52)

src/views/BrokeringRoute.vue
=> Fixed: route when navigating from routes to runs page after multiple navigations

src/components/TimezoneModal.vue
=> Implemented: spinner to be displayed when fetching of timeZones is in progress

src/views/BrokeringQuery.vue
=> Implemented: support for asking user before page change when any edits are made on the page(#69)

src/theme/variables.css, src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue, src/views/BrokeringRuns.vue
Closes #63 
Added cursor: pointer on the components that are clickable to have a better UX.
Added the defined class on following places:
- Runs card
- Routes card
- Route status
- Rule Status
=> Fixed: clickable items to have a pointer to have a better UX by defining a global pointer class and added it on the required components(#63)

src/components/GroupHistoryModal.vue, src/locales/en.json, src/services/RoutingService.ts, src/utils/index.ts, src/views/BrokeringRoute.vue, src/views/BrokeringRuns.vue
=> Implemented: support to display the run history for the current run(#64)

src/views/BrokeringQuery.vue
=> Fixed: shipping method options to display the description in place of id

src/views/BrokeringQuery.vue
=> Fixed: undefined error for facilityName for order filters(#84)

src/views/Login.vue, src/views/Settings.vue
=> Improved: login page to use composition api pattern

src/services/UserService.ts
=> Fixed: logic to display toast message on login

src/views/BrokeringQuery.vue
=> Improved: UI for the filter cards

src/views/BrokeringQuery.vue
=> Improved: status maintaining feature to change status only using select and remove the toggle option for status change on route details page(#92)

src/views/BrokeringQuery.vue
=> Improved: handling when failed to fetch the routing Rule information(#106)

package-lock.json, package.json
=> Improved: app version in package and lock file for major release(v1.0.0)

src/views/BrokeringQuery.vue
Closes #116 
This will help the user in routing the order from multiple channels at once.
After:
=> Implemented: support to enable multiple selection for sales channel option for routing filters(#116)

src/views/BrokeringRoute.vue
=> Improved: logic to change the status of routing even when the status is active(#115)

src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue
=> Improved: UI to update the width for the order routing filters section and added slots for filter selector icon

src/components/GroupHistoryModal.vue, src/utils/index.ts, src/views/BrokeringRoute.vue
=> Improved: time formatting and delta value when displaying time(#118)

src/utils/index.ts, src/views/BrokeringRoute.vue, src/views/BrokeringRuns.vue
=> Fixed: the schedule time and timeDiff as the execution time has been changed from seconds to millis(#130)

src/views/BrokeringRoute.vue
Related Issue #113 
- Save description on enter
- Focus on the description area when clicking edit/add button
- Added condition to not change the line on enter and just save the description and the line can be changed using a combination of shift+enter
- Replaced \n with br tag to correctly display multi-line desc
- 
Mutli-line support:
=> Implemented: support to save the description on enter(#113) 

src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue
Related Issue #141
Added check to not save the ruleName or routeName with empty values
=> Improved: check for rule and route name fields(#141)

src/components/AddInventoryFilterOptionsModal.vue, src/components/AddOrderRouteFilterOptions.vue
=> Implemented: support to disable the save button if there are no changes in the filter options(#140)

src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue
=> Improved: the sequence of status options and added subheader in popover(#160)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.1.0)

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
=> Update FEATURE_REQUEST.md for adding label automatically

src/views/BrokeringRoute.vue
=> Implemented: support to edit groupName(#181)

src/views/BrokeringQuery.vue
=> Improved: chip to wrap it inside div as the click event gets triggered when clicking outside of the chip(#167)

src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue
Related Issue #162
Added check for backdrop dismiss
=> Improved: code to not redirect user to previous page when user clicks the backdrop for closing the alert(#162)

src/api/index.ts
=> Implemented: support to login into the app using full url

src/services/UserService.ts
=> Fixed: case to check for full url when using client method

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.2.0)

package-lock.json, package.json
=> Improved: app version in package and lock file for patch release(v1.2.1)

src/services/RoutingService.ts, src/store/modules/orderRouting/actions.ts, src/views/BrokeringRoute.vue
=> Implemented: support to fetch the latest routing history and fetch the history by startDate

src/locales/en.json, src/views/Settings.vue
=> Improved: code to disable the goToOms button when redirectionUrl is not found and added go to launchpad button(#219)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.3.0)

src/store/modules/user/actions.ts
=> Fixed: typo in redirection action name on logout

src/views/BrokeringRoute.vue
=> Improved: UI to make the save button fixed in the UI when there are any unsaved changes on routes page(#207)

src/views/BrokeringQuery.vue, src/views/BrokeringRoute.vue, src/views/BrokeringRuns.vue
=> Updated: icon for status option(#228)

src/services/UtilService.ts, src/store/modules/util/actions.ts, src/views/BrokeringQuery.vue
=> Improved: endpoint for fetching enums related to sales channel(#235)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.4.0)

src/components/ScheduleModal.vue, src/locales/en.json
=> Improved: updated locale file to make static text entry(#245)

package-lock.json, package.json
=> Updated: app version for minor release v1.6.0

src/components/AddInventoryFilterOptionsModal.vue
=> Removed: shipment threshold check option from inventory filters as its support is not yet available in the app

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release and updated lock file for missing deps(v1.7.0)

src/store/modules/util/actions.ts
=> Fixed: issue of duplicate filter options being visible in exclude segment(#248)

package-lock.json, package.json
=> Improved: version in package and lock file for minor release(v1.8.0)
